name:                SimpleLambda
version:             0.1.0.0
github:              "RyanMcNamara/SimpleLambda"
license:             MIT
author:              "Ryan McNamara"
maintainer:          "gn341ram@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on GitHub at <https://github.com/RyanMcNamara/SimpleLambda#readme>

dependencies:
- base >= 4.7 && < 5
- lens >= 4.8
- hashmap >= 1.3.2

library:
  source-dirs: src

executables:
  SimpleLambda:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SimpleLambda

tests:
  SimpleLambda-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SimpleLambda
    - hspec
    - QuickCheck
    - test-invariant
